imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:bootstrap_package/Configuration/RTE/Default.yaml" }

editor:
    config:
        contentsCss: "EXT:t3_gabarit_basic/Resources/Public/Css/rte.css"
